server:
  port: 9292

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: identity
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/identity_server_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true