version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_server_db